#pragma once

#include "CoreMinimal.h"
#include "Modules/ModuleInterface.h"
#include "Modules/ModuleManager.h"
#include "UnrealEd.h"

#include <KismetEditorUtilities.h>

DECLARE_LOG_CATEGORY_EXTERN(ColonyEditorLog, All, All)

class FColonyEditorModule : public IModuleInterface
{

public:
	virtual void StartupModule() override;
	virtual void ShutdownModule() override;

private:

#define RegisterDefaultEvent(Class, FuncName) \
    (FKismetEditorUtilities::RegisterAutoGeneratedDefaultEvent(this, Class::StaticClass(), GET_FUNCTION_NAME_CHECKED(Class, FuncName)));

	void PrepareAutoGeneratedDefaultEvents();

	void RegisterUnmutableSettings();
	void UnregisterUnmutableSettings();

	bool HandleSaved();
};