// Fill out your copyright notice in the Description page of Project Settings.

#include "ColonyEditorModule.h"

#include <KismetEditorUtilities.h>
#include <ISettingsModule.h>
#include <ISettingsContainer.h>
#include <ISettingsSection.h>
#include "Core/Settings/ColonyAISettings.h"
#include "Core/Settings/ColonyManagers.h"
#include "AI/Plan/Stage.h"
#include "AI/Stages/MoveTo.h"
#include "ColonyGridSettings.h"

IMPLEMENT_MODULE(FColonyEditorModule, ColonyEditor);
DEFINE_LOG_CATEGORY(ColonyEditorLog)

void FColonyEditorModule::StartupModule()
{
	UE_LOG(ColonyEditorLog, Log, TEXT("ColonyEditor: Module Started"));

	PrepareAutoGeneratedDefaultEvents();
	RegisterUnmutableSettings();
}

void FColonyEditorModule::ShutdownModule()
{
	UE_LOG(ColonyEditorLog, Warning, TEXT("ColonyEditor: Module Shutdown"));

	FKismetEditorUtilities::UnregisterAutoBlueprintNodeCreation(this);
	
	UnregisterUnmutableSettings();
}

void FColonyEditorModule::PrepareAutoGeneratedDefaultEvents()
{
	RegisterDefaultEvent(UStage, Start);
	RegisterDefaultEvent(UStage, StageTick);

	RegisterDefaultEvent(UMoveTo, SetMoveToLocation);
	RegisterDefaultEvent(UMoveTo, SetTargetBuildingID);
}

void FColonyEditorModule::RegisterUnmutableSettings()
{
	if (ISettingsModule* SettingsModule = FModuleManager::GetModulePtr<ISettingsModule>("Settings"))
	{
		ISettingsContainerPtr SettingsContainer = SettingsModule->GetContainer("Project");

		SettingsContainer->DescribeCategory("Colony Settings", FText::FromString("Colony Settings"), FText::FromString("Base settings for all Colony specific settings"));

		ISettingsSectionPtr AISection = SettingsModule->RegisterSettings("Project", "Colony Settings", "AI", FText::FromString("Colony AI Settings"), FText::FromString("Base settings for all Colony AI"), GetMutableDefault<UColonyAISettings>());
		ISettingsSectionPtr ManagerSection = SettingsModule->RegisterSettings("Project", "Colony Settings", "Managers", FText::FromString("Colony Managers"), FText::FromString("Managers to spin up on GameInstant Init - put dependant managers as late as possible in array"), GetMutableDefault<UColonyManagers>());
		ISettingsSectionPtr GridSection = SettingsModule->RegisterSettings("Project", "Colony Settings", "Grid", FText::FromString("Colony Grid"), FText::FromString("Settings pertaining to the Colony Building Grid, and how it is rendered"), GetMutableDefault<UColonyGridSettings>());

		if (AISection.IsValid() && ManagerSection.IsValid())
		{
			AISection->OnModified().BindRaw(this, &FColonyEditorModule::HandleSaved);
		}
	}
}

void FColonyEditorModule::UnregisterUnmutableSettings()
{
	if (ISettingsModule* SettingsModule = FModuleManager::GetModulePtr<ISettingsModule>("Settings"))
	{
		SettingsModule->UnregisterSettings("Project", "Colony Settings", "AI");
		SettingsModule->UnregisterSettings("Project", "Colony Settings", "Managers");
		SettingsModule->UnregisterSettings("Project", "Colony Settings", "Grid");
	}
}

bool FColonyEditorModule::HandleSaved()
{
	UColonyAISettings* AISettings = GetMutableDefault<UColonyAISettings>();
	AISettings->SaveConfig();

	UColonyManagers* ColonyManagers = GetMutableDefault<UColonyManagers>();
	ColonyManagers->SaveConfig();

	UColonyGridSettings* ColonyGridSettings = GetMutableDefault<UColonyGridSettings>();
	ColonyGridSettings->SaveConfig();

	return true;
}
